export const userConstants = {

    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    TOTAL_CONTACT_SUCCESS: 'TOTAL_CONTACT_SUCCESS',
    TOTAL_CONTACT_FAILURE: 'TOTAL_CONTACT_FAILURE',
    ADD_CONTACT_SUCCESS: 'ADD_CONTACT_SUCCESS',
    ADD_CONTACT_FAILURE: 'ADD_CONTACT_FAILURE',
    UPDATE_CONTACT_SUCCESS: 'UPDATE_CONTACT_SUCCESS',
    UPDATE_CONTACT_FAILURE: 'UPDATE_CONTACT_FAILURE',
    DELETE_CONTACT_SUCCESS: 'DELETE_CONTACT_SUCCESS',
    DELETE_CONTACT_FAILURE: 'DELETE_CONTACT_FAILURE',
    CALL_COUNT_SUCCESS: "CALL_COUNT_SUCCESS",
    CALL_COUNT_FAILURE: "CALL_COUNT_FAILURE"


};
